In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# to observe all the column
pd.set_option("display.max_columns",None)

In [3]:
# importing the dataset
df=pd.read_csv(r"D:\SKILLEDGES PUNE\Datasets\Equity Data (1 Jan 2020).csv")
df

,DATE1,SYMBOL,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,11-02-2022,NETFLTGILT,22.40,22.02,22.48,22.02,22.25,22.27,22.25,16697,3.72,83,12968.0,77.67
1,11-02-2022,NETFMID150,116.02,119.50,119.50,113.61,114.10,113.95,114.68,224822,257.82,1780,200777.0,89.30
2,11-02-2022,NETFNIF100,183.49,178.50,184.98,178.50,182.05,182.22,182.07,2354,4.29,135,2140.0,90.91
3,11-02-2022,NETFDIVOPP,45.63,46.25,46.25,45.07,45.33,45.09,45.40,1239,0.56,86,1122.0,90.56
4,11-02-2022,NETFGILT5Y,49.66,49.66,49.82,49.47,49.82,49.79,49.72,82821,41.18,322,74512.0,89.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809334,01-01-2020,ORTINLABSS,9.90,10.15,10.15,9.80,9.85,9.80,9.84,5041,0.50,26,4283.0,84.96
809335,01-01-2020,ORISSAMINE,1281.50,1270.00,1288.00,1259.35,1264.00,1265.60,1268.53,8230,104.40,626,4091.0,49.71
809336,01-01-2020,OSWALAGRO,4.95,5.15,5.40,5.00,5.20,5.30,5.18,27820,1.44,143,17849.0,64.16
809337,01-01-2020,PAISALO,433.00,429.95,438.00,427.45,429.95,428.85,432.68,37838,163.72,505,8873.0,23.45
809338,01-01-2020,PAGEIND,23393.10,23350.00,23799.00,23241.10,23600.00,23602.15,23601.26,16716,3945.19,6464,2964.0,17.73

In [4]:
# to observe top 5 data
df.head()

,DATE1,SYMBOL,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,11-02-2022,NETFLTGILT,22.40,22.02,22.48,22.02,22.25,22.27,22.25,16697,3.72,83,12968.0,77.67
1,11-02-2022,NETFMID150,116.02,119.50,119.50,113.61,114.10,113.95,114.68,224822,257.82,1780,200777.0,89.30
2,11-02-2022,NETFNIF100,183.49,178.50,184.98,178.50,182.05,182.22,182.07,2354,4.29,135,2140.0,90.91
3,11-02-2022,NETFDIVOPP,45.63,46.25,46.25,45.07,45.33,45.09,45.40,1239,0.56,86,1122.0,90.56
4,11-02-2022,NETFGILT5Y,49.66,49.66,49.82,49.47,49.82,49.79,49.72,82821,41.18,322,74512.0,89.97

In [5]:
# size of the dataset
df.shape

(809339, 14)

In [6]:
# to see the datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 809339 entries, 0 to 809338
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0    DATE1          809339 non-null  object
 1   SYMBOL          809339 non-null  object
 2    PREV_CLOSE     809339 non-null  float64
 3    OPEN_PRICE     809339 non-null  float64
 4    HIGH_PRICE     809339 non-null  float64
 5    LOW_PRICE      809339 non-null  float64
 6    LAST_PRICE     809339 non-null  float64
 7    CLOSE_PRICE    809339 non-null  float64
 8    AVG_PRICE      809339 non-null  float64
 9    TTL_TRD_QNTY   809339 non-null  int64
 10   TURNOVER_LACS  809339 non-null  float64
 11   NO_OF_TRADES   809339 non-null  int64
 12   DELIV_QTY      809336 non-null  float64
 13   DELIV_PER      809336 non-null  float64
dtypes: float64(10), int64(2), object(2)
memory usage: 86.4+ MB

In [7]:
# Above we can see that date is a object type ,so i have to change the date to date-datatype
df[' DATE1'] = pd.to_datetime(df[' DATE1'])
df['Month'] = df[' DATE1'].dt.month
df['Year'] = df[' DATE1'].dt.year

In [8]:
df = df.sort_values(by=' DATE1')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 809339 entries, 809338 to 34525
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0    DATE1          809339 non-null  datetime64[ns]
 1   SYMBOL          809339 non-null  object
 2    PREV_CLOSE     809339 non-null  float64
 3    OPEN_PRICE     809339 non-null  float64
 4    HIGH_PRICE     809339 non-null  float64
 5    LOW_PRICE      809339 non-null  float64
 6    LAST_PRICE     809339 non-null  float64
 7    CLOSE_PRICE    809339 non-null  float64
 8    AVG_PRICE      809339 non-null  float64
 9    TTL_TRD_QNTY   809339 non-null  int64
 10   TURNOVER_LACS  809339 non-null  float64
 11   NO_OF_TRADES   809339 non-null  int64
 12   DELIV_QTY      809336 non-null  float64
 13   DELIV_PER      809336 non-null  float64
 14  Month           809339 non-null  int64
 15  Year            809339 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(4), object(1)
memory usage: 105.0+ MB

In [10]:
# to check null values
df.isnull().sum()

 DATE1            0
SYMBOL            0
 PREV_CLOSE       0
 OPEN_PRICE       0
 HIGH_PRICE       0
 LOW_PRICE        0
 LAST_PRICE       0
 CLOSE_PRICE      0
 AVG_PRICE        0
 TTL_TRD_QNTY     0
 TURNOVER_LACS    0
 NO_OF_TRADES     0
 DELIV_QTY        3
 DELIV_PER        3
Month             0
Year              0
dtype: int64

In [11]:
# removing that row who have null values
df.dropna(inplace=True)

In [12]:
df.isnull().sum()

 DATE1            0
SYMBOL            0
 PREV_CLOSE       0
 OPEN_PRICE       0
 HIGH_PRICE       0
 LOW_PRICE        0
 LAST_PRICE       0
 CLOSE_PRICE      0
 AVG_PRICE        0
 TTL_TRD_QNTY     0
 TURNOVER_LACS    0
 NO_OF_TRADES     0
 DELIV_QTY        0
 DELIV_PER        0
Month             0
Year              0
dtype: int64

In [13]:
df.shape

(809336, 16)

In [14]:
# calculate the percentage gain or loss based on prev close with today's close.
df['%_change'] = ( ( df[' CLOSE_PRICE'] - df[' PREV_CLOSE'] )/df[' PREV_CLOSE'] )*100

In [15]:
data = df.groupby(['SYMBOL','Year','Month']).agg({'%_change': ['sum']})
data

                       %_change
                            sum
SYMBOL    Year Month
20MICRONS 2020 1       1.544431
               2      -9.965604
               3      21.167205
               4      17.745787
               5       7.580387
...                         ...
ZYDUSWELL 2022 8      -0.549334
               9      -1.505357
               10     -2.588053
               11     -5.374437
               12      1.238986

[62887 rows x 1 columns]

In [16]:
data_group_new = data.reset_index()

In [17]:
# Now go through every year and every month to find top 10  best performing stocks.
count = 0
for i in data_group_new['Year'].unique():
    
    new = data_group_new[data_group_new['Year'] == i]
    for j in new['Month'].unique():
        
        
        listofindex = new[new['Month'] == j]['%_change'].sort_values(by='sum',ascending=False).head(10).index.to_list()
        count += 1
        print("IN year {i}: IN {j} Month : Top 10 Performing Stocks :".format(i=i,j=j))
        
        
        for k in listofindex:
            print(df['SYMBOL'].iloc[k])
        print('\n')
print("Total Months:",count)

IN year 2020: IN 1 Month : Top 10 Performing Stocks :
JBFIND
CHOLAFIN
RUSHIL
GOLDENTOBC
SOMATEX
KAJARIACER
ICICI500
IOC
OCCL
COALINDIA


IN year 2020: IN 2 Month : Top 10 Performing Stocks :
HBLPOWER
VIDHIING
CAMLINFINE
NIFTYEES
JAYBARMARU
SHILPAMED
NAHARPOLY
ARENTERP
SESHAPAPER
CHAMBLFERT


IN year 2020: IN 3 Month : Top 10 Performing Stocks :
MANAKCOAT
FMGOETZE
GREENLAM
JBMA
RSWM
TRITURBINE
MOIL
TITAN
MANAKCOAT
SYNGENE


IN year 2020: IN 4 Month : Top 10 Performing Stocks :
MANAPPURAM
TRIL
CERA
RICOAUTO
SANGHIIND
MARICO
ASAL
ASTRAMICRO
INDORAMA
SANDHAR


IN year 2020: IN 5 Month : Top 10 Performing Stocks :
EQ30
COLPAL
SHREDIGCEM
BLS
TEXMOPIPES
MOTHERSUMI
VBL
ABSLBANETF
MASFIN
ASIANHOTNR


IN year 2020: IN 6 Month : Top 10 Performing Stocks :
VOLTAS
ARVINDFASN
BHAGYAPROP
SHIVAMAUTO
TIRUMALCHM
NETFCONSUM
LICHSGFIN
APOLLOTYRE
GUJGASLTD
COMPINFO


IN year 2020: IN 7 Month : Top 10 Performing Stocks :
ACE
ORIENTELEC
LALPATHLAB
AMRUTANJAN
GEPIL
ADANIGAS
ANANTRAJ
SANGHVIMOV
FCONSUMER
SIMBHALS


IN year 2020: IN 8 Month : Top 10 Performing Stocks :
LICHSGFIN
PRIMESECU
AGROPHOS
SICAL
KABRAEXTRU
JMA
PEARLPOLY
HGINFRA
SASKEN
STARPAPER


IN year 2020: IN 9 Month : Top 10 Performing Stocks :
HIKAL
AGROPHOS
DAAWAT
AARVEEDEN
EROSMEDIA
RALLIS
LEMONTREE
PONNIERODE
ICICINXT50
WESTLIFE


IN year 2020: IN 10 Month : Top 10 Performing Stocks :
UJJIVAN
QNIFTY
INDOCO
CCL
MAHESHWARI
MTEDUCARE
HLVLTD
ITC
SUZLON
MAYURUNIQ


IN year 2020: IN 11 Month : Top 10 Performing Stocks :
HNDFDS
KINGFA
NCLIND
AKSHARCHEM
ELECON
CUBEXTUB
FORCEMOT
INDIANB
GEEKAYWIRE
PARAGMILK


IN year 2020: IN 12 Month : Top 10 Performing Stocks :
VARDHACRLC
LUXIND
AXISGOLD
KIRLOSIND
INDRAMEDCO
OPTOCIRCUI
JKCEMENT
ADANIGREEN
THEINVEST
BALMLAWRIE


IN year 2021: IN 1 Month : Top 10 Performing Stocks :
FINPIPE
ICICISENSX
APTECHT
SHAHALLOYS
PODDARMENT
HONAUT
SHANKARA
NECLIFE
NATIONALUM
SHANTIGEAR


IN year 2021: IN 2 Month : Top 10 Performing Stocks :
TITAN
STAMPEDE
ICICIBANK
AMRUTANJAN
SUPERHOUSE
INDHOTEL
QUESS
RAYMOND
HONAUT
PFOCUS


IN year 2021: IN 3 Month : Top 10 Performing Stocks :
CGPOWER
UFO
METROPOLIS
RBLBANK
ONEPOINT
SHARDACROP
IDFNIFTYET
ELGIRUBCO
WORTH
TAKE


IN year 2021: IN 4 Month : Top 10 Performing Stocks :
TCI
KEI
BLKASHYAP
MMFL
ZOTA
TGBHOTELS
NIFTYBEES
GOKULAGRO
CERA
SRIPIPES


IN year 2021: IN 5 Month : Top 10 Performing Stocks :
ASHIMASYN
HITECHGEAR
AMDIND
PNB
ONWARDTEC
IDBIGOLD
SADBHIN
UNICHEMLAB
KITEX
IDFC


IN year 2021: IN 6 Month : Top 10 Performing Stocks :
CTE
GRANULES
MANAKALUCO
OISL
SNOWMAN
GUJALKALI
OIL
XCHANGING
JBMA
ORIENTABRA


IN year 2021: IN 7 Month : Top 10 Performing Stocks :
ICICIBANK
KOTAKBKETF
MIRCELECTR
VIKASWSP
CEBBCO
GANESHHOUC
ARSHIYA
PGHH
SOMICONVEY
LALPATHLAB


IN year 2021: IN 8 Month : Top 10 Performing Stocks :
NETFNIF100
RML
POLYMED
UTTAMSTL
FINEORG
TCNSBRANDS
AGCNET
DCBBANK
FCL
GRINDWELL


IN year 2021: IN 9 Month : Top 10 Performing Stocks :
PAISALO
ADFFOODS
ABAN
JUSTDIAL
TEXRAIL
HDFC
ADANIENT
BEL
ICICIB22
MUKANDENGG


IN year 2021: IN 10 Month : Top 10 Performing Stocks :
ALPA
NAVKARCORP
TIPSINDLTD
SHIL
VIKASPROP
SIEMENS
DECCANCE
LAMBODHARA
JAICORPLTD
GALLANTT


IN year 2021: IN 11 Month : Top 10 Performing Stocks :
GRPLTD
NITINSPIN
GOLDBEES
OMAXAUTO
SAKUMA
MOIL
ONEPOINT
HPL
DONEAR
ARIHANTSUP


IN year 2021: IN 12 Month : Top 10 Performing Stocks :
COALINDIA
SUBEX
BHAGYANGR
5PAISA
SWARAJENG
DENORA
BOROSIL
TITAN
SAKSOFT
HIL


IN year 2022: IN 1 Month : Top 10 Performing Stocks :
SABTN
GUJAPOLLO
ALBK
MAN50ETF
PURVA
PRAKASHSTL
SNOWMAN
SRIPIPES
ICICINIFTY
OCCL


IN year 2022: IN 2 Month : Top 10 Performing Stocks :
HNDFDS
NETFCONSUM
TANLA
UTINEXT50
SJVN
S&SPOWER
IOC
SIS
BAJAJELEC
WESTLIFE


IN year 2022: IN 3 Month : Top 10 Performing Stocks :
SDBL
NAVINFLUOR
DREDGECORP
MINDTREE
3IINFOTECH
SRHHYPOLTD
VADILALIND
SREINFRA
APTECHT
THYROCARE


IN year 2022: IN 4 Month : Top 10 Performing Stocks :
HIRECT
DEEPENR
HDFCBANK
WHEELS
EICHERMOT
MINDACORP
RTNINFRA
JAYAGROGN
FINPIPE
VAISHALI


IN year 2022: IN 5 Month : Top 10 Performing Stocks :
AMRUTANJAN
ASTEC
PGHH
SREEL
GODFRYPHLP
PANACEABIO
KEYFINSERV
RGL
SHILPAMED
KOTAKPSUBK


IN year 2022: IN 6 Month : Top 10 Performing Stocks :
TAINWALCHM
VIPIND
FLEXITUFF
KOTAKNV20
GMBREW
ABCAPITAL
ANANTRAJ
ASIANTILES
ANDHRSUGAR
DABUR


IN year 2022: IN 7 Month : Top 10 Performing Stocks :
FELDVR
LEMONTREE
PERSISTENT
VINYLINDIA
SBILIFE
LPDC
HITECHGEAR
MSTCLTD
ALPA
ORIENTPPR


IN year 2022: IN 8 Month : Top 10 Performing Stocks :
TEXRAIL
VEDL
SBIETFQLTY
GOLDENTOBC
RBL
EXCELINDUS
PALREDTEC
RAYMOND
WABCOINDIA
SIMPLEXINF


IN year 2022: IN 9 Month : Top 10 Performing Stocks :
SIMBHALS
DLINKINDIA
BIRLACABLE
GILLANDERS
HINDALCO
PATINTLOG
HDFCMFGETF
HARRMALAYA
NMDC
ALKYLAMINE


IN year 2022: IN 10 Month : Top 10 Performing Stocks :
PFS
ADFFOODS
JUBILANT
SOLARA
NIITTECH
NPBET
CHAMBLFERT
SINTEX
ANDHRAPAP
TIJARIA


IN year 2022: IN 11 Month : Top 10 Performing Stocks :
BIL
CENTEXT
RUPA
MARUTI
UJJIVANSFB
PETRONET
HIL
ESSELPACK
GOODLUCK
BHAGYANGR


IN year 2022: IN 12 Month : Top 10 Performing Stocks :
ALICON
SOUTHWEST
GANECOS
UTINIFTETF
NDGL
BSOFT
EVERESTIND
DATAMATICS
VIDHIING
KABRAEXTRU


Total Months: 36

In [18]:
# Now go through every year and every month to find top 10 non best performing stocks.
count = 0
for i in data_group_new['Year'].unique():
    
    new = data_group_new[data_group_new['Year'] == i]
    for j in new['Month'].unique():
        listofindex = new[new['Month'] == j]['%_change'].sort_values(by='sum',ascending=False).tail(10).index.to_list()
        count += 1
        print("IN year {i}: IN {j} Month : Top 10 Non Performing Stocks :".format(i=i,j=j))
        for k in listofindex:
            print(df['SYMBOL'].iloc[k])
        print('\n')
print("Total Months:",count)

IN year 2020: IN 1 Month : Top 10 Non Performing Stocks :
BHARATRAS
CHEMCON
SONATSOFTW
SOMANYCERA
SUNTV
CTE
CANTABIL
TAINWALCHM
ADVANIHOTR
LIQUIDETF


IN year 2020: IN 2 Month : Top 10 Non Performing Stocks :
20MICRONS
NILKAMAL
BHAGYAPROP
BHAGYANGR
KRBL
KUANTUM
KMSUGAR
RAMANEWS
KARDA
TECHNOE


IN year 2020: IN 3 Month : Top 10 Non Performing Stocks :
UNITEDTEA
PATINTLOG
5PAISA
PSUBNKBEES
GREENLAM
ATFL
UNIPLY
TATAMETALI
PIONDIST
NAGREEKCAP


IN year 2020: IN 4 Month : Top 10 Non Performing Stocks :
MOTOGENFIN
ADFFOODS
VETO
EKC
WILLAMAGOR
NELCAST
PNBGILTS
KOTAKGOLD
SOTL
DELTAMAGNT


IN year 2020: IN 5 Month : Top 10 Non Performing Stocks :
SAGCEM
ABSLNN50ET
PSPPROJECT
HUDCO
MARATHON
MANINDS
VIKASECO
SANDHAR
JAYSREETEA
ONWARDTEC


IN year 2020: IN 6 Month : Top 10 Non Performing Stocks :
IDBIGOLD
RSSOFTWARE
SUPERHOUSE
TATACHEM
ALLSEC
ORIENTALTL
KAKATCEM
CENTEXT
SOBHA
LUXIND


IN year 2020: IN 7 Month : Top 10 Non Performing Stocks :
ASAL
IFCI
RUPA
AGROPHOS
LAOPALA
WALCHANNAG
SURYALAXMI
IIFLSEC
VIKASECO
TRIL


IN year 2020: IN 8 Month : Top 10 Non Performing Stocks :
AMBUJACEM
SALONA
NETFDIVOPP
LOTUSEYE
UTISENSETF
SANGHVIMOV
LICNETFN50
NETFCONSUM
SAIL
CORALFINAC


IN year 2020: IN 9 Month : Top 10 Non Performing Stocks :
NH
GSKCONS
MSPL
ULTRACEMCO
ALBK
IOB
KOTAKBKETF
FCL
GHCL
MANGCHEFER


IN year 2020: IN 10 Month : Top 10 Non Performing Stocks :
GALLANTT
TIRUMALCHM
MANALIPETC
LUMAXIND
THYROCARE
ELECON
BAJFINANCE
MEGH
MAN50ETF
TREEHOUSE


IN year 2020: IN 11 Month : Top 10 Non Performing Stocks :
KALPATPOWR
THERMAX
MANALIPETC
SAKUMA
AEGISCHEM
AVADHSUGAR
VSTTILLERS
JTEKTINDIA
IMFA
SETFNIFBK


IN year 2020: IN 12 Month : Top 10 Non Performing Stocks :
WILLAMAGOR
TATAMETALI
ASIANPAINT
THOMASCOOK
MADHUCON
ORIENTBELL
TATACHEM
MMP
APEX
JHS


IN year 2021: IN 1 Month : Top 10 Non Performing Stocks :
VAKRANGEE
SGL
JCHAC
PGEL
AIRAN
BLUEDART
KOTARISUG
TORNTPOWER
KIRLOSENG
CENTUM


IN year 2021: IN 2 Month : Top 10 Non Performing Stocks :
GDL
COLPAL
CANTABIL
ISMTLTD
MAGNUM
KENNAMET
ASTRAZEN
MANINFRA
KSCL
KOKUYOCMLN


IN year 2021: IN 3 Month : Top 10 Non Performing Stocks :
SAIL
IGL
APOLLOTYRE
MUNJALAU
MARUTI
EMAMILTD
BALPHARMA
ISFT
HNDFDS
RUCHIRA


IN year 2021: IN 4 Month : Top 10 Non Performing Stocks :
PETRONET
HCLTECH
MANAPPURAM
UCALFUEL
PGIL
ICICIBANK
GRSE
FLUOROCHEM
SAFARI
MANAKSTEEL


IN year 2021: IN 5 Month : Top 10 Non Performing Stocks :
ATULAUTO
FINEORG
PGHL
REFEX
EQUITAS
EDELWEISS
MOLDTKPAC
KIRIINDUS
MAHABANK
CENTENKA


IN year 2021: IN 6 Month : Top 10 Non Performing Stocks :
INDIANB
IRCON
GRPLTD
BEARDSELL
HERCULES
DVL
JMFINANCIL
GODREJIND
INDBANK
IVP


IN year 2021: IN 7 Month : Top 10 Non Performing Stocks :
QNIFTY
VAIBHAVGBL
BIRLACORPN
BPL
CENTRUM
VLSFINANCE
JPASSOCIAT
IVP
RATNAMANI
TRIVENI


IN year 2021: IN 8 Month : Top 10 Non Performing Stocks :
CHAMBLFERT
GRINDWELL
INDHOTEL
ASAHIINDIA
WHIRLPOOL
ARIHANT
RVNL
TITAN
JINDALPOLY
KREBSBIO


IN year 2021: IN 9 Month : Top 10 Non Performing Stocks :
TVSMOTOR
STARPAPER
ICICILIQ
KESORAMIND
JAGSNPHARM
CARERATING
TCPLPACK
IGL
VIKASWSP
SAIL


IN year 2021: IN 10 Month : Top 10 Non Performing Stocks :
SHIVATEX
RUCHI
BYKE
JUBLFOOD
CAPACITE
SOMATEX
SRTRANSFIN
ACC
ARVINDFASN
CORALFINAC


IN year 2021: IN 11 Month : Top 10 Non Performing Stocks :
ENIL
SANGHIIND
L&TFH
APOLLOHOSP
SRIPIPES
KRBL
MANAKCOAT
MUNJALAU
MCDHOLDING
MAHASTEEL


IN year 2021: IN 12 Month : Top 10 Non Performing Stocks :
STERTOOLS
OMKARCHEM
MIRZAINT
CAREERP
ASHIMASYN
CYIENT
RCF
UNITEDTEA
TEXMOPIPES
APLAPOLLO


IN year 2022: IN 1 Month : Top 10 Non Performing Stocks :
ORIENTALTL
INDIGO
CENTUM
GENESYS
SUTLEJTEX
HIMATSEIDE
PETRONET
VTL
LICNETFN50
TITAN


IN year 2022: IN 2 Month : Top 10 Non Performing Stocks :
INDTERRAIN
ARVINDFASN
UNIVCABLES
ZEEL
DCM
AFFLE
AMBUJACEM
STCINDIA
TATAPOWER
LALPATHLAB


IN year 2022: IN 3 Month : Top 10 Non Performing Stocks :
CENTRUM
BHARATRAS
SHRIRAMEPC
AVADHSUGAR
SIMPLEXINF
KIRLOSENG
JAGRAN
LAKSHVILAS
INDSWFTLTD
DIAMONDYD


IN year 2022: IN 4 Month : Top 10 Non Performing Stocks :
JKIL
PRICOLLTD
KOTHARIPET
L&TFH
XCHANGING
BHAGYANGR
NIFTYEES
VAISHALI
ARVINDFASN
BAJAJHLDNG


IN year 2022: IN 5 Month : Top 10 Non Performing Stocks :
KIRLOSBROS
HITECHGEAR
BAGFILMS
ASAHIINDIA
BURNPUR
CSBBANK
MTNL
NIITTECH
SWSOLAR
TCNSBRANDS


IN year 2022: IN 6 Month : Top 10 Non Performing Stocks :
ALKALI
GSPL
FORCEMOT
LAOPALA
MERCATOR
INDIGO
RAMANEWS
INDUSINDBK
MBLINFRA
THEINVEST


IN year 2022: IN 7 Month : Top 10 Non Performing Stocks :
BAJAJFINSV
MFSL
SRF
AXISCADES
KOTHARIPET
GODREJIND
KOTAKNIFTY
OIL
BBTC
INOXLEISUR


IN year 2022: IN 8 Month : Top 10 Non Performing Stocks :
KSCL
M&MFIN
DMART
VESUVIUS
ORIENTBANK
MANINFRA
RUBYMILLS
BALAJITELE
GUJALKALI
INDIANHUME


IN year 2022: IN 9 Month : Top 10 Non Performing Stocks :
AMDIND
SYNDIBANK
BIRLATYRE
JINDRILL
GODREJPROP
ESSARSHPNG
TEXMOPIPES
ASIANTILES
REDINGTON
WABAG


IN year 2022: IN 10 Month : Top 10 Non Performing Stocks :
SUPREMEIND
GOLDENTOBC
RELIGARE
SRF
GUJALKALI
ASIANPAINT
LICNETFGSC
INDOTHAI
GPPL
INDNIPPON


IN year 2022: IN 11 Month : Top 10 Non Performing Stocks :
AGCNET
ZUARI
RITES
THEMISMED
WILLAMAGOR
BASML
PARSVNATH
MEGH
INDOSTAR
CEATLTD


IN year 2022: IN 12 Month : Top 10 Non Performing Stocks :
NAVINFLUOR
ALKALI
STEELCITY
INFRABEES
GILLANDERS
IGARASHI
FAIRCHEM
IDFCFIRSTB
RATNAMANI
SIMPLEXINF


Total Months: 36